name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: Rewynd Apk
          path: app/build/outputs/apk/debug/Rewynd.apk
